### ISSUE TITLE
Improve multiple login behaviour when not using a VPN (Throttling)

### ISSUE THREAD

**Issue by SamMackrill** [SamMackrill/gw2-alternator#149]
Thread for discussion.
If you login too many times on a single IP address then ArenaNet will slow-down access and eventually block the IP
There is logic and settings to slow things down and help prevent this however it is not well documented on how this works and the approach needs testing.

My intention is to improve the approach so it is easier to understand and has reasonable defaults
Some of the assumptions and behaviour I have gathered from various sources:

* ArenaNet's anti-botting measures tend to make dealing with more than 10 accounts difficult
    - There is a hard limit of 40 accounts from a single IP address, resets every 8 hours
    - Logging into many (>10? ) accounts on https://www.guildwars2.com/ may cause a lockout that takes 24 hours to clear
    - Logging into the game will become slower after multiple (>10?) accounts and may block entirely
    - Waiting a few minutes (5?) will help

GW2-Alternator tries to counter this by slowing down the login attempts after a failure (throttling)
However the delay required depends on the past login history and is difficult to guess
There are tuning parameters in Settings to help adjust this:

![image](https://user-images.githubusercontent.com/84898/234312202-0db9a9de-23a6-4285-9644-d24ec4f11f9b.png)

this means:
1-12 accounts have a 0s delay
13-24 accounts have a 30s delay
25-40 accounts have a 45s delay

above that it is set to band3 + 60s

If a login fails then the delay is set to
`40 + 20 * ConsecutiveFailCount`

**Comment by Caliban2017** [comment]
I'm not sure if it is helping to extend the time between the Logins to avoid the IP Block. I think it is more working like 20 Accounts in 4-5 Hours, then you can begin again... so this is what i have noticed. 

In the last Weeks i did ~20 Accounts in the Morning (arround 8-9 AM) and waited until 1-2 PM and did one more 20 Accounts and waited till 9-10 PM and 20 Accounts again. This worked without any Problems in the last Weeks/Months. But i believe there is a maximum of Accounts in a given Timewindow of 4-5h. I don't know if you can expand it to more Accounts in this Timewindow by wait more between the Logins... but of course i can try it.. So i could increase the Band times to test it?

**Comment by Caliban2017** [comment]
> @Caliban2017 Do you have the 'Force Serial' option checked? I don't use a VPN and I'm able to run the logins with no issues. It takes ~15min to run through all 37 of my accounts with the Force Serial option enabled.

Yes, i use always the Serial Function, because without it triggers the IP Ban much faster. I played now a little bit with the Band Times and it seems i had success. I raised Band 1 to 10/15s, Band 2 24/45s and Band 3 40/45s. It took a bit longer but in run trough without IP Ban this time, but i only had 2-3 failed Logins. Maybe this is not helping anymore, when more Logins are failing. But it seems tuning is helping here to avoid the IP Ban. I don't know why the Credentials are always missing, a friend told me he does not have this Problem. Maybe the Accounts itself got flagged or something? It is so random which Accounts lose their Data...

**Comment by SamMackrill** [comment]
Interesting we are trying to guess the strategy that the login servers use, so the more information the better.

**Comment by SamMackrill** [comment]
Here is my non-VPN login with 30/45/45 delays, it is quite slow and there are still failures but no IP lockouts or manual intervention

Started	2023-04-26	08:32:08	?	1.0.35
Total Time	2079.6068866	s
Attempts\Fails	42	6	1.167
Account	Start	Authenticate	Login	Enter	Exit
Fish2	0.5645259	4.0717581	15.9526548	1.0952104
Hugo	31.9599961	3.9693248	16.0300738	1.0825802
Fish3	63.346761	4.3197195	13.764878	1.1772868
Sophia	94.6815432	3.9266256	15.5611374	1.0866285
Fish20	125.9552362	4.2693487	13.6451305	1.1858822
Fish22	157.2813893			40.0328693
Fish21	199.473917	4.2845976	13.8097557	1.0676096
Fish23	230.9055725	4.2651099		63.2133332
Fish22	301.1155829	3.9544061	13.6811935	1.094332
Fish23	362.4590079	3.7349993	13.4198636	1.5773157
Fish4	393.8321459	4.3293977	13.4393526	1.1946862
Fish6	425.3464381	5.2929789	10.9720576	1.1538405
Fish5	471.7034037	4.1984855	15.4655662	1.3015811
Fish7	518.0657507	5.3171121	13.243625	1.1358505
Fish8	564.4162071	4.1863782	15.9652722	1.1452927
Fish9	610.7809622	5.2150009	11.1114195	1.1234543
Fish13	657.1114385	4.0755276	13.6466087	1.1247819
Fish12	703.5389158	4.3817845	15.4900811	1.2432463
Fish10	749.8290451	4.3216267	15.2560519	1.3721099
Fish14	796.5044299	4.1441056	12.8828747	1.1513512
Fish15	842.9623481	4.0512011	13.4977646	1.1452472
Fish11	889.408798	4.2551798	14.2024886	1.1519992
Fish16	935.8797899	4.1549628	15.8239112	1.1478114
Fish17	982.2234943	4.1968574	19.8352447	1.1384964
Fish25	1028.5903761	39.4174184		37.0543441
Fish24	1107.1521175	4.3962123	19.4361323	1.088958
Fish18	1153.8781417	4.1626063	22.5853469	1.1404079
Fish26	1200.2688793	4.4924461	24.8487257	1.1236152
Fish19	1246.6888401	15.3932675	13.2452682	1.1235081
Fish28	1293.1251947	4.3025876	26.2727147	1.1100865
Fish27	1339.5721801	4.3944066	29.1919927	1.1259789
Fish29	1385.896253			40.2863725
Fish31	1432.2924114	4.1008805	28.1830109	1.0861051
Fish29	1478.8465791	4.2075937	30.8834261	1.1140409
Fish30	1525.2037328	4.2619839	30.9189936	1.09123
Fish25	1571.5362077	4.0211322	32.8956089	1.0953746
Fish32	1617.972281	4.9682107		87.3887314
Fish33	1712.4413728	16.5083713	22.7201161	1.1747165
Fish34	1773.9942764	7.515915	35.0585549	1.1213196
Fish35	1820.380395	3.9443961		35.8752538
Fish35	1926.6410114	3.7323673	38.6378553	1.1117311
Fish32	2033.0780289	4.028063	39.3056685	1.1108463

**Comment by SamMackrill** [comment]
New release with improved Throttle logging https://github.com/SamMackrill/gw2-alternator/releases/tag/V1.0.34
Have a look at the gw2-alternator-launch-Login-log.txt

2023-04-26 09:48:30.8758|Fish17 Started Login process=24836
2023-04-26 09:48:31.0903|Fish17 Change State to Started because Normal Start
2023-04-26 09:48:31.0903|Fish17 KillMutex: WaitForInputIdle on process=24836
2023-04-26 09:48:31.9196|Fish17 Killed Mutex
2023-04-26 09:48:32.1250|Fish17 Release Login
2023-04-26 09:48:32.1483|Fish17 LoginDone Login
2023-04-26 09:48:32.1735|Fish17 login semaphore released, count=1
2023-04-26 09:48:32.2220|Fish17 Authentication No VPN release delay=45s because Band 3 (count=24)
2023-04-26 09:48:32.2220|Fish17 Authentication Throttle set: 45s because Band 3 (count=24)
2023-04-26 09:48:34.6393|Fish17 Change State to ReadyToLogin because Module umpdc.dll loaded
2023-04-26 09:48:35.0659|Fish17 Change State to ReadyToPlay because Memory(kB) 488 > 200
2023-04-26 09:48:41.9975|Fish17 Change State to Playing because Module d3d11.dll loaded
2023-04-26 09:48:48.4731|Fish17 Change State to CharacterSelection because Memory(MB) 549 > 500
2023-04-26 09:48:54.9007|Fish17 Change State to CharacterSelected because Memory(MB) 769 > 600
2023-04-26 09:48:55.7110|Fish17 Kill GW2 process=24836
2023-04-26 09:48:56.0316|Fish17 Change State to Exited because Process.Exit event
2023-04-26 09:48:56.0316|Fish17 GW2 process exited because Success

**Comment by Caliban2017** [comment]
I tested the 1.0.34 but it will still not work correct for me. I still experience Errors while starting the Game. I tested now 25 other Accounts with the higher Thresholds but with that many Errors that occours, it is a veeeery long process, takes about 1 hour for these 25 Accounts, because the Throttle gets higher and higher (over 100 Seconds).

When the Error comes, the Game starts, login and the Game is loading and then it closes and instant it restarts again, but does not Login. The Login button get not pressed automatically. Some of my Accounts at Attemp 5 or Higher, because of so many Erros. Of course the IP Ban get triggered much faster. This is really not usable, sadly it is easier to fill in all missing Login Credentials manually and use the old Thresholds. Here again a Log of a failed Login (not missing Credentials, it just not login into the Game):

2023-04-26 14:21:26.9758|RunStatus: Running
2023-04-26 14:21:26.9758|Started Login process=12468
2023-04-26 14:21:27.1964|Change State to Started because Normal Start
2023-04-26 14:21:27.1964|RunStage: Started
2023-04-26 14:21:27.1964|lastStageMemoryUsage set: 23.168kB
2023-04-26 14:21:27.1964|Status changed from NotRun to Started
2023-04-26 14:21:27.1964|KillMutex: WaitForInputIdle on process=12468
2023-04-26 14:21:27.6450|KillMutex: Delay
2023-04-26 14:21:27.8531|KillMutex: GetHandle
2023-04-26 14:21:27.8724|Got handle to Mutex
2023-04-26 14:21:27.8724|Killed Mutex
2023-04-26 14:21:28.0881|Release Login
2023-04-26 14:21:28.0881|login semaphore released, count=0
2023-04-26 14:21:28.0881|Authentication Throttle set: 45s because Band 3 (count=38)
2023-04-26 14:21:28.0881|Memory(kB) current=173.168 last=23.168 Δ=150.000
2023-04-26 14:21:28.0881|Stage(kB)  current=173.168 last=23.168 Δ=150.000
2023-04-26 14:21:28.0881|Module: gw2-64.exe
2023-04-26 14:21:28.0881|Module: ntdll.dll
2023-04-26 14:21:28.0881|Module: kernel32.dll
2023-04-26 14:21:28.0881|Module: kernelbase.dll
2023-04-26 14:21:28.0881|Module: apphelp.dll
2023-04-26 14:21:28.0881|Module: aclayers.dll
2023-04-26 14:21:28.0881|Module: msvcrt.dll
2023-04-26 14:21:28.0881|Module: shlwapi.dll
2023-04-26 14:21:28.0881|Module: sortwindows61.dll
2023-04-26 14:21:28.0881|Module: user32.dll
2023-04-26 14:21:28.0881|Module: win32u.dll
2023-04-26 14:21:28.0881|Module: gdi32.dll
2023-04-26 14:21:28.0881|Module: gdi32full.dll
2023-04-26 14:21:28.0881|Module: msvcp_win.dll
2023-04-26 14:21:28.0881|Module: ucrtbase.dll
2023-04-26 14:21:28.0881|Module: advapi32.dll
2023-04-26 14:21:28.0881|Module: sechost.dll
2023-04-26 14:21:28.0881|Module: rpcrt4.dll
2023-04-26 14:21:28.0881|Module: ws2_32.dll
2023-04-26 14:21:28.0881|Module: version.dll
2023-04-26 14:21:28.0881|Module: wintrust.dll
2023-04-26 14:21:28.0881|Module: wtsapi32.dll
2023-04-26 14:21:28.0881|Module: winmm.dll
2023-04-26 14:21:28.0881|Module: ole32.dll
2023-04-26 14:21:28.0881|Module: combase.dll
2023-04-26 14:21:28.0881|Module: oleaut32.dll
2023-04-26 14:21:28.0881|Module: shell32.dll
2023-04-26 14:21:28.0881|Module: msacm32.dll
2023-04-26 14:21:28.0881|Module: crypt32.dll
2023-04-26 14:21:28.0881|Module: gdiplus.dll
2023-04-26 14:21:28.0881|Module: comctl32.dll
2023-04-26 14:21:28.0881|Module: usp10.dll
2023-04-26 14:21:28.0881|Module: msimg32.dll
2023-04-26 14:21:28.0881|Module: secur32.dll
2023-04-26 14:21:28.0881|Module: cryptbase.dll
2023-04-26 14:21:28.0881|Module: sspicli.dll
2023-04-26 14:21:28.0881|Module: imm32.dll
2023-04-26 14:21:28.0881|Module: msasn1.dll
2023-04-26 14:21:28.0881|Module: bcryptprimitives.dll
2023-04-26 14:21:28.0881|Module: dbghelp.dll
2023-04-26 14:21:28.0881|Module: windows.storage.dll
2023-04-26 14:21:28.0881|Module: wintypes.dll
2023-04-26 14:21:28.0881|Module: shcore.dll
2023-04-26 14:21:28.0881|Module: profapi.dll
2023-04-26 14:21:28.0881|Module: kernel.appcore.dll
2023-04-26 14:21:28.0881|Module: devobj.dll
2023-04-26 14:21:28.0881|Module: cfgmgr32.dll
2023-04-26 14:21:28.0881|Module: dxcore.dll
2023-04-26 14:21:28.0881|Module: uxtheme.dll
2023-04-26 14:21:28.0881|Module: cryptnet.dll
2023-04-26 14:21:28.0881|Module: imagehlp.dll
2023-04-26 14:21:28.0881|Module: cryptsp.dll
2023-04-26 14:21:28.0881|Module: rsaenh.dll
2023-04-26 14:21:28.0881|Module: bcrypt.dll
2023-04-26 14:21:28.0881|Module: drvstore.dll
2023-04-26 14:21:28.0881|Module: wldp.dll
2023-04-26 14:21:28.0881|Module: gpapi.dll
2023-04-26 14:21:28.0881|Module: clbcatq.dll
2023-04-26 14:21:28.0881|Module: ntmarta.dll
2023-04-26 14:21:28.0881|Module: napinsp.dll
2023-04-26 14:21:28.0881|Module: pnrpnsp.dll
2023-04-26 14:21:28.0881|Module: mswsock.dll
2023-04-26 14:21:28.0881|Module: dnsapi.dll
2023-04-26 14:21:28.0881|Module: iphlpapi.dll
2023-04-26 14:21:28.0881|Module: nsi.dll
2023-04-26 14:21:28.0881|Module: winrnr.dll
2023-04-26 14:21:28.0881|Module: wshbth.dll
2023-04-26 14:21:28.0881|Module: nlansp_c.dll
2023-04-26 14:21:28.0881|Module: fwpuclnt.dll
2023-04-26 14:21:28.0881|Module: rasadhlp.dll
2023-04-26 14:21:28.0881|Module: msctf.dll
2023-04-26 14:21:28.0881|Module: textinputframework.dll
2023-04-26 14:21:28.0881|Module: windowscodecs.dll
2023-04-26 14:21:28.0881|Module: textshaping.dll
2023-04-26 14:21:28.3119|Memory(kB) current=193.216 last=173.168 Δ=20.048
2023-04-26 14:21:28.3119|Stage(kB)  current=193.216 last=23.168 Δ=170.048
2023-04-26 14:21:28.7511|Memory(kB) current=238.964 last=145.720 Δ=93.244
2023-04-26 14:21:28.7511|Stage(kB)  current=238.964 last=23.168 Δ=215.796
2023-04-26 14:21:28.7653|Module: libcef.dll
2023-04-26 14:21:28.7653|Module: comdlg32.dll
2023-04-26 14:21:28.7653|Module: propsys.dll
2023-04-26 14:21:28.7653|Module: dxgi.dll
2023-04-26 14:21:28.7653|Module: uiautomationcore.dll
2023-04-26 14:21:28.7653|Module: oleacc.dll
2023-04-26 14:21:28.7653|Module: userenv.dll
2023-04-26 14:21:28.7653|Module: hid.dll
2023-04-26 14:21:28.7653|Module: netapi32.dll
2023-04-26 14:21:28.7653|Module: chrome_elf.dll
2023-04-26 14:21:28.7653|Module: dwrite.dll
2023-04-26 14:21:28.7653|Module: ncrypt.dll
2023-04-26 14:21:28.7653|Module: dwmapi.dll
2023-04-26 14:21:28.7653|Module: winspool.drv
2023-04-26 14:21:28.7653|Module: d3d9.dll
2023-04-26 14:21:28.7653|Module: dxva2.dll
2023-04-26 14:21:28.7653|Module: cryptui.dll
2023-04-26 14:21:28.7653|Module: urlmon.dll
2023-04-26 14:21:28.7653|Module: winhttp.dll
2023-04-26 14:21:28.7653|Module: credui.dll
2023-04-26 14:21:28.7653|Module: dhcpcsvc.dll
2023-04-26 14:21:28.7653|Module: wevtapi.dll
2023-04-26 14:21:28.7653|Module: wininet.dll
2023-04-26 14:21:28.7653|Module: esent.dll
2023-04-26 14:21:28.7653|Module: srvcli.dll
2023-04-26 14:21:28.7653|Module: iertutil.dll
2023-04-26 14:21:28.7653|Module: netutils.dll
2023-04-26 14:21:28.7653|Module: dsrole.dll
2023-04-26 14:21:28.7653|Module: wkscli.dll
2023-04-26 14:21:28.7653|Module: samcli.dll
2023-04-26 14:21:28.7653|Module: ntasn1.dll
2023-04-26 14:21:28.7653|Module: dpapi.dll
2023-04-26 14:21:28.7653|Module: dhcpcsvc6.dll
2023-04-26 14:21:28.7653|Module: textservice_x64.dll
2023-04-26 14:21:28.7653|Module: winsta.dll
2023-04-26 14:21:28.7653|Module: mmdevapi.dll
2023-04-26 14:21:28.7653|Module: mscms.dll
2023-04-26 14:21:28.7653|Module: dsreg.dll
2023-04-26 14:21:29.4106|Memory(kB) current=215.820 last=215.792 Δ=28
2023-04-26 14:21:29.4106|Stage(kB)  current=215.820 last=23.168 Δ=192.652
2023-04-26 14:21:29.6332|Memory(kB) current=215.912 last=215.820 Δ=92
2023-04-26 14:21:29.6332|Stage(kB)  current=215.912 last=23.168 Δ=192.744
2023-04-26 14:21:29.6332|Module: powrprof.dll
2023-04-26 14:21:29.6332|Module: umpdc.dll
2023-04-26 14:21:29.8530|Change State to ReadyToLogin because Module umpdc.dll loaded
2023-04-26 14:21:29.8530|RunStage: ReadyToLogin
2023-04-26 14:21:29.8530|lastStageMemoryUsage set: 215.912kB
2023-04-26 14:21:29.8530|Status changed from Started to ReadyToLogin
2023-04-26 14:21:29.8530|Send ENTER from ReadyToLogin
2023-04-26 14:21:30.0598|Memory(kB) current=217.656 last=215.912 Δ=1.744
2023-04-26 14:21:30.0598|Stage(kB)  current=217.656 last=215.912 Δ=1.744
2023-04-26 14:21:30.0598|ReadyToLogin Threshold(kB): 1.744>200
2023-04-26 14:21:30.2604|Change State to ReadyToPlay because Memory(kB) 1744 > 200
2023-04-26 14:21:30.2604|RunStage: ReadyToPlay
2023-04-26 14:21:30.2604|lastStageMemoryUsage set: 217.656kB
2023-04-26 14:21:30.2604|Status changed from ReadyToLogin to ReadyToPlay
2023-04-26 14:21:30.2604|Send ENTER from ReadyToPlay
2023-04-26 14:21:30.2768|Module: coremessaging.dll
2023-04-26 14:21:30.2768|Module: coreuicomponents.dll
2023-04-26 14:21:30.4846|Memory(kB) current=217.708 last=217.656 Δ=52
2023-04-26 14:21:30.4846|Stage(kB)  current=217.708 last=217.656 Δ=52
2023-04-26 14:21:31.1458|Memory(kB) current=217.656 last=217.632 Δ=24
2023-04-26 14:21:31.1458|Stage(kB)  current=217.656 last=217.656 Δ=0
2023-04-26 14:21:31.3653|Memory(kB) current=217.684 last=217.656 Δ=28
2023-04-26 14:21:31.3653|Stage(kB)  current=217.684 last=217.656 Δ=28
2023-04-26 14:21:31.5854|Memory(kB) current=217.708 last=217.684 Δ=24
2023-04-26 14:21:31.5854|Stage(kB)  current=217.708 last=217.656 Δ=52
2023-04-26 14:21:31.8059|Memory(kB) current=217.796 last=217.708 Δ=88
2023-04-26 14:21:31.8059|Stage(kB)  current=217.796 last=217.656 Δ=140
2023-04-26 14:21:32.0270|Memory(kB) current=217.840 last=217.796 Δ=44
2023-04-26 14:21:32.0270|Stage(kB)  current=217.840 last=217.656 Δ=184
2023-04-26 14:21:32.2461|Memory(kB) current=217.856 last=217.840 Δ=16
2023-04-26 14:21:32.2461|Stage(kB)  current=217.856 last=217.656 Δ=200
2023-04-26 14:21:32.4674|Memory(kB) current=217.900 last=217.856 Δ=44
2023-04-26 14:21:32.4674|Stage(kB)  current=217.900 last=217.656 Δ=244
2023-04-26 14:21:32.4674|Enter Request StageΔ 244kB
2023-04-26 14:21:32.4674|Send ENTER from engine
2023-04-26 14:21:32.9058|Memory(kB) current=217.776 last=217.728 Δ=48
2023-04-26 14:21:32.9058|Stage(kB)  current=217.776 last=217.656 Δ=120
2023-04-26 14:21:33.1265|Memory(kB) current=217.784 last=217.776 Δ=8
2023-04-26 14:21:33.1265|Stage(kB)  current=217.784 last=217.656 Δ=128
2023-04-26 14:21:33.3467|Memory(kB) current=217.816 last=217.784 Δ=32
2023-04-26 14:21:33.3467|Stage(kB)  current=217.816 last=217.656 Δ=160
2023-04-26 14:21:33.5657|Memory(kB) current=217.852 last=217.816 Δ=36
2023-04-26 14:21:33.5657|Stage(kB)  current=217.852 last=217.656 Δ=196
2023-04-26 14:21:34.0049|Memory(kB) current=217.152 last=217.072 Δ=80
2023-04-26 14:21:34.0049|Stage(kB)  current=217.152 last=217.656 Δ=-504
2023-04-26 14:21:34.2263|Memory(kB) current=217.176 last=217.152 Δ=24
2023-04-26 14:21:34.2263|Stage(kB)  current=217.176 last=217.656 Δ=-480
2023-04-26 14:21:34.6642|Enter Request StageΔ -480kB
2023-04-26 14:21:34.6642|Send ENTER from engine
2023-04-26 14:21:34.8861|Memory(kB) current=217.260 last=217.176 Δ=84
2023-04-26 14:21:34.8861|Stage(kB)  current=217.260 last=217.656 Δ=-396
2023-04-26 14:21:35.3272|Memory(kB) current=217.292 last=217.260 Δ=32
2023-04-26 14:21:35.3272|Stage(kB)  current=217.292 last=217.656 Δ=-364
2023-04-26 14:21:35.9878|Memory(kB) current=217.480 last=217.292 Δ=188
2023-04-26 14:21:35.9878|Stage(kB)  current=217.480 last=217.656 Δ=-176
2023-04-26 14:21:36.6445|Memory(kB) current=217.500 last=217.484 Δ=16
2023-04-26 14:21:36.6445|Stage(kB)  current=217.500 last=217.656 Δ=-156
2023-04-26 14:21:36.8645|Memory(kB) current=217.564 last=217.500 Δ=64
2023-04-26 14:21:36.8645|Stage(kB)  current=217.564 last=217.656 Δ=-92
2023-04-26 14:21:36.8645|Enter Request StageΔ -92kB
2023-04-26 14:21:36.8645|Send ENTER from engine
2023-04-26 14:21:37.7447|Memory(kB) current=217.884 last=217.568 Δ=316
2023-04-26 14:21:37.7447|Stage(kB)  current=217.884 last=217.656 Δ=228
2023-04-26 14:21:37.9649|Memory(kB) current=217.972 last=217.884 Δ=88
2023-04-26 14:21:37.9649|Stage(kB)  current=217.972 last=217.656 Δ=316
2023-04-26 14:21:38.4067|Memory(kB) current=218.076 last=217.972 Δ=104
2023-04-26 14:21:38.4067|Stage(kB)  current=218.076 last=217.656 Δ=420
2023-04-26 14:21:38.6284|Memory(kB) current=219.196 last=218.076 Δ=1.120
2023-04-26 14:21:38.6284|Stage(kB)  current=219.196 last=217.656 Δ=1.540
2023-04-26 14:21:39.0700|Enter Request StageΔ 1.540kB
2023-04-26 14:21:39.0700|Send ENTER from engine
2023-04-26 14:21:39.3060|Memory(kB) current=282.636 last=219.196 Δ=63.440
2023-04-26 14:21:39.3060|Stage(kB)  current=282.636 last=217.656 Δ=64.980
2023-04-26 14:21:39.3250|Module: amd_ags_x64.dll
2023-04-26 14:21:39.3250|Module: vcruntime140.dll
2023-04-26 14:21:39.3250|Module: nvapi64.dll
2023-04-26 14:21:39.3250|Module: setupapi.dll
2023-04-26 14:21:39.3250|Module: d3d11.dll
2023-04-26 14:21:39.3250|Module: directxdatabasehelper.dll
2023-04-26 14:21:39.3250|Module: nvldumdx.dll
2023-04-26 14:21:39.3250|Module: nvwgf2umx.dll
2023-04-26 14:21:39.3250|Module: dcomp.dll
2023-04-26 14:21:39.5401|Change State to Playing because Module d3d11.dll loaded
2023-04-26 14:21:39.5401|RunStage: Playing
2023-04-26 14:21:39.5401|lastStageMemoryUsage set: 457.580kB
2023-04-26 14:21:39.5401|Status changed from ReadyToPlay to Playing
2023-04-26 14:21:39.7475|Memory(kB) current=484.296 last=282.636 Δ=201.660
2023-04-26 14:21:39.7475|Stage(kB)  current=484.296 last=457.580 Δ=26.716
2023-04-26 14:21:39.7664|Module: winmmbase.dll
2023-04-26 14:21:39.7664|Module: wdmaud.drv
2023-04-26 14:21:39.7664|Module: ksuser.dll
2023-04-26 14:21:39.7664|Module: avrt.dll
2023-04-26 14:21:39.7664|Module: audioses.dll
2023-04-26 14:21:39.7664|Module: msacm32.drv
2023-04-26 14:21:39.7664|Module: midimap.dll
2023-04-26 14:21:39.7664|Module: resourcepolicyclient.dll
2023-04-26 14:21:39.9827|Memory(kB) current=490.596 last=484.296 Δ=6.300
2023-04-26 14:21:39.9827|Stage(kB)  current=490.596 last=457.580 Δ=33.016
2023-04-26 14:21:40.2179|Memory(kB) current=491.408 last=490.596 Δ=812
2023-04-26 14:21:40.2179|Stage(kB)  current=491.408 last=457.580 Δ=33.828
2023-04-26 14:21:40.4526|Memory(kB) current=501.460 last=491.408 Δ=10.052
2023-04-26 14:21:40.4526|Stage(kB)  current=501.460 last=457.580 Δ=43.880
2023-04-26 14:21:40.6751|Memory(kB) current=507.128 last=501.460 Δ=5.668
2023-04-26 14:21:40.6751|Stage(kB)  current=507.128 last=457.580 Δ=49.548
2023-04-26 14:21:40.9089|Memory(kB) current=508.172 last=507.128 Δ=1.044
2023-04-26 14:21:40.9089|Stage(kB)  current=508.172 last=457.580 Δ=50.592
2023-04-26 14:21:41.1310|Memory(kB) current=517.956 last=508.172 Δ=9.784
2023-04-26 14:21:41.1310|Stage(kB)  current=517.956 last=457.580 Δ=60.376
2023-04-26 14:21:41.1310|Enter Request StageΔ 60.376kB
2023-04-26 14:21:41.1310|Send ENTER from engine
2023-04-26 14:21:41.3648|Memory(kB) current=524.120 last=517.956 Δ=6.164
2023-04-26 14:21:41.3648|Stage(kB)  current=524.120 last=457.580 Δ=66.540
2023-04-26 14:21:41.5991|Memory(kB) current=525.148 last=524.120 Δ=1.028
2023-04-26 14:21:41.5991|Stage(kB)  current=525.148 last=457.580 Δ=67.568
2023-04-26 14:21:41.8344|Memory(kB) current=531.084 last=525.148 Δ=5.936
2023-04-26 14:21:41.8344|Stage(kB)  current=531.084 last=457.580 Δ=73.504
2023-04-26 14:21:42.0704|Memory(kB) current=536.492 last=531.084 Δ=5.408
2023-04-26 14:21:42.0704|Stage(kB)  current=536.492 last=457.580 Δ=78.912
2023-04-26 14:21:42.2906|Memory(kB) current=547.016 last=536.492 Δ=10.524
2023-04-26 14:21:42.2906|Stage(kB)  current=547.016 last=457.580 Δ=89.436
2023-04-26 14:21:42.5261|Memory(kB) current=547.784 last=547.016 Δ=768
2023-04-26 14:21:42.5261|Stage(kB)  current=547.784 last=457.580 Δ=90.204
2023-04-26 14:21:42.7616|Memory(kB) current=558.264 last=547.784 Δ=10.480
2023-04-26 14:21:42.7616|Stage(kB)  current=558.264 last=457.580 Δ=100.684
2023-04-26 14:21:42.9954|Memory(kB) current=564.424 last=558.264 Δ=6.160
2023-04-26 14:21:42.9954|Stage(kB)  current=564.424 last=457.580 Δ=106.844
2023-04-26 14:21:43.2304|Memory(kB) current=570.584 last=564.424 Δ=6.160
2023-04-26 14:21:43.2304|Stage(kB)  current=570.584 last=457.580 Δ=113.004
2023-04-26 14:21:43.2304|Enter Request StageΔ 113.004kB
2023-04-26 14:21:43.2304|Send ENTER from engine
2023-04-26 14:21:43.4659|Memory(kB) current=628.052 last=570.584 Δ=57.468
2023-04-26 14:21:43.4659|Stage(kB)  current=628.052 last=457.580 Δ=170.472
2023-04-26 14:21:43.7001|Memory(kB) current=702.948 last=628.052 Δ=74.896
2023-04-26 14:21:43.7001|Stage(kB)  current=702.948 last=457.580 Δ=245.368
2023-04-26 14:21:43.9203|Memory(kB) current=773.064 last=702.948 Δ=70.116
2023-04-26 14:21:43.9203|Stage(kB)  current=773.064 last=457.580 Δ=315.484
2023-04-26 14:21:44.1553|Memory(kB) current=849.272 last=773.064 Δ=76.208
2023-04-26 14:21:44.1553|Stage(kB)  current=849.272 last=457.580 Δ=391.692
2023-04-26 14:21:44.3899|Memory(kB) current=926.720 last=849.272 Δ=77.448
2023-04-26 14:21:44.3899|Stage(kB)  current=926.720 last=457.580 Δ=469.140
2023-04-26 14:21:44.3899|Playing Threshold(MB): 458>400
2023-04-26 14:21:44.5929|Change State to CharacterSelection because Memory(MB) 458 > 400
2023-04-26 14:21:44.5929|RunStage: CharacterSelection
2023-04-26 14:21:44.5929|lastStageMemoryUsage set: 926.720kB
2023-04-26 14:21:44.5929|Status changed from Playing to CharacterSelection
2023-04-26 14:21:44.5929|Send ENTER from SelectCharacter
2023-04-26 14:21:44.5929|GW2 Hide
2023-04-26 14:21:44.6173|Module: icm32.dll
2023-04-26 14:21:46.6230|Memory(kB) current=1.152.364 last=926.720 Δ=225.644
2023-04-26 14:21:46.6230|Stage(kB)  current=1.152.364 last=926.720 Δ=225.644
2023-04-26 14:21:46.6230|Enter Request StageΔ 225.644kB
2023-04-26 14:21:46.6230|Send ENTER from engine
2023-04-26 14:21:48.6516|Change State to Exited because Process.Exit event
2023-04-26 14:21:48.6516|RunStage: Exited
2023-04-26 14:21:48.6516|lastStageMemoryUsage set: 926.720kB
2023-04-26 14:21:48.6516|Status changed from CharacterSelection to Exited
2023-04-26 14:21:48.6516|GW2 process 12468 exited because Crashed
2023-04-26 14:21:48.6516|This exit was unexpected
2023-04-26 14:21:48.6516|Process 12468 is Dead
2023-04-26 14:21:48.6516|RunStatus: Error
2023-04-26 14:21:48.6516|launch failed|guildwars2.tools.alternator.Gw2CrashedException: GW2 process crashed
   at guildwars2.tools.alternator.MVVM.model.Client.Launch(LaunchType launchType, Settings settings, Boolean shareArchive, Boolean accountLogs, DirectoryInfo applicationFolder, VpnDetails vpn, CancellationToken cancellationToken)
   at guildwars2.tools.alternator.Launcher.LaunchAsync(FileInfo loginFile, DirectoryInfo applicationFolder, FileInfo gfxSettingsFile, Boolean shareArchive, Boolean logAccount, AuthenticationThrottle authenticationThrottle, SemaphoreSlim loginSemaphore, SemaphoreSlim exeSemaphore)
2023-04-26 14:21:48.6516|exe semaphore released, count=0

**Comment by Caliban2017** [comment]
The new Login Log give something like this, when a Login does not work:

2023-04-26 14:22:58.7723|XXX@XXX.com Started Login process=9588
2023-04-26 14:22:58.9788|XXX@XXX.com Change State to Started because Normal Start
2023-04-26 14:22:58.9788|XXX@XXX.com KillMutex: WaitForInputIdle on process=9588
2023-04-26 14:22:59.4570|XXX@XXX.com Change State to Exited because Process.Exit event
2023-04-26 14:22:59.4570|XXX@XXX.com GW2 process exited because Crashed
2023-04-26 14:22:59.4570|XXX@XXX.com Release Login
2023-04-26 14:22:59.4570|XXX@XXX.com LoginDone Login
2023-04-26 14:22:59.4570|XXX@XXX.com login semaphore released, count=1
2023-04-26 14:22:59.4602|XXX@XXX.com Authentication No VPN release delay=105s because Band > 3 (count=40)
2023-04-26 14:22:59.4602|XXX@XXX.com Authentication Throttle set: 105s because Band > 3 (count=40)
